package in.ineuron.model;
// Generated Nov 8, 2023, 4:58:19 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insurancepolicy generated by hbm2java
 */
@Entity
@Table(name = "insurancepolicy", catalog = "telusko")
public class Insurancepolicy implements java.io.Serializable {

	private int policyId;
	private String policyName;
	private String policyType;
	private String company;
	private Integer tenure;

	public Insurancepolicy() {
	}

	public Insurancepolicy(int policyId) {
		this.policyId = policyId;
	}

	public Insurancepolicy(int policyId, String policyName, String policyType, String company, Integer tenure) {
		this.policyId = policyId;
		this.policyName = policyName;
		this.policyType = policyType;
		this.company = company;
		this.tenure = tenure;
	}

	@Id

	@Column(name = "policyId", unique = true, nullable = false)
	public int getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(int policyId) {
		this.policyId = policyId;
	}

	@Column(name = "policyName", length = 20)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "policyType", length = 10)
	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	@Column(name = "company", length = 10)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "tenure")
	public Integer getTenure() {
		return this.tenure;
	}

	public void setTenure(Integer tenure) {
		this.tenure = tenure;
	}

	@Override
	public String toString() {
		return "Insurancepolicy [policyId=" + policyId + ", policyName=" + policyName + ", policyType=" + policyType
				+ ", company=" + company + ", tenure=" + tenure + "]";
	}

	
}
